# Generated by Django 4.2 on 2023-04-03 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(choices=[('dn', 'Daily News'), ('sp', 'Sport'), ('cu', 'Culture'), ('mu', 'Music'), ('bu', 'Business')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Article name')),
                ('image', models.URLField(default='https://cdn.pixabay.com/photo/2018/02/12/16/35/phonograph-record-3148686__340.jpg')),
                ('text', models.CharField(default='', max_length=5000)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.section')),
            ],
        ),
    ]
